name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: cordova
        run: npm install -g cordova

      - name: Ionic
        run: npm install -g @ionic/cli
      
      - name: npm
        run: npm install
      
#       - name: typings
#         run: npm install -g @ionic/app-scripts
        
      - name: Remove Android platform
        run: ionic cordova platform rm android
        
      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Build Android Dev APK
        run: ionic cordova build android

      - name: Build Android Release APK
        run: ionic cordova build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

#       - name: Upload release bundle
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release
#           path: platforms/android/app/build/outputs/bundle/release/app.aab
